[package]
name = "bookdb"
version = "0.2.0"
edition = "2021"
authors = ["qodeninja <1043235+qodeninja@users.noreply.github.com>"]
description = "boook."
license = "MIT"
repository = "https://github.com/rustadex/bookdb"
readme = "README.md"
keywords = ["rdx", "rustadex" ]
categories = ["command-line-interface"]
publish = false





[dependencies]
clap = { version = "4.5", features = ["derive"] }
# The 'backup' feature is required for the .backup() method
rusqlite = { version = "0.31", features = ["bundled", "backup"] }
xdg = "2.5"
log = "0.4"
env_logger = "0.11"
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true

base64 = "0.22"
