// src/bookdb/service/db/data/mod.rs
// SQL data directory module
// This module contains SQL files and related constants

// SQL constants are generated by build.rs at compile time
// The generated constants will be available through include!() macros

pub mod sqlv1 {
    // V1 SQL constants would be included here
}

pub mod sqlv2 {
    // V2 SQL constants would be included here
}